import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    backgroundColor:'#eaf6ff',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    justifyContent: 'center',
  },
  headerIcon: {
    height:50,
    width:50,
    left:-20,
  },
  headerText: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2C3E50',
    left:-15,
  },
  card: {
    backgroundColor: "#9c9ad5",
    borderRadius: 20,
    padding: 24,
    minWidth: 280,
    maxWidth: 380,
  },
  welcomeTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#b24b27',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#FFF',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  googleButton: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 50,
    padding: 14,
    alignItems: 'center',
    justifyContent: "space-evenly",
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  googleIcon: {
    height:22,
    width:22,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
    left:-15,
  },
  fastLoginText: {
    fontSize: 12,
    color: '#FFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  studentButton: {
    backgroundColor: '#3D4A7D',
    borderRadius: 50,
    padding: 14,
    alignItems: 'center',
    // marginBottom: 16,
    marginTop:16,
  },
  studentButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  dividerText: {
    marginHorizontal: 10,
    color: '#FFF',
    fontSize: 14,
    fontWeight: '500',
  },
  otpConatiner:{
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical:12,
    paddingHorizontal:10,
    borderRadius:10,
  },
  otpTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    marginBottom: 12,
    gap: 8,
  },
  countryCodeButton: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems:"center",
    minWidth: 60,
  },
  countryCodeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    textAlign: 'center',
  },
  phoneInput: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#2C3E50',
    fontWeight:"500",
  },
  sendOtpButton: {
    backgroundColor: '#3D4A7D',
    borderRadius: 50,
    padding: 14,
    alignItems: 'center',
    marginBottom: 14,
  },
  sendOtpButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
  },
  verifyInput:{
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#2C3E50',
    fontWeight:"500",
    minWidth:150,
    maxHeight:50
  },
  editText:{
    fontSize:16,
    color:"#fff",
    fontWeight:"400",
    textDecorationLine:"underline",
    textDecorationStyle:"solid"
  },
  guestContainer:{
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical:12,
    paddingHorizontal:10,
    borderRadius:10,
  },
  guestButton: {
    borderRadius: 50,
    padding: 5,
    alignItems: 'center',
    marginBottom: 5,
  },
  guestButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFF',
  },
  signupGuestButton: {
    backgroundColor: '#3D4A7D',
    borderRadius: 50,
    padding: 14,
    alignItems: 'center',
  },
  signupGuestButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFF',
  },
  whatsappButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#25D366',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  whatsappIcon: {
    fontSize: 28,
  },
});

export default styles;