import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  quizHeaderContainer: {
    backgroundColor: "#3d4a72",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 20,
  },
  quizMainTitle: {
    fontSize: 36,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 20,
    textAlign: "center",
  },
  infoCardsContainer: {
    marginBottom: 20,
  },
  infoCard: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginBottom: 12,
    alignItems: "center",
  },
  infoValue: {
    fontSize: 22,
    fontWeight: "700",
    color: "#fbbf24",
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 14,
    color: "#cbd5e0",
  },
  primaryButton: {
    backgroundColor: "#ed8936",
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#cbd5e0",
  },
  shareHelperText: {
    fontSize: 13,
    color: "#a0aec0",
    textAlign: "center",
    marginBottom: 20,
  },
  trophyContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 16,
    height: 120,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  trophyEmoji: {
    fontSize: 56,
  },
  progressSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3748",
  },
  progressPercent: {
    fontSize: 16,
    fontWeight: "600",
    color: "#718096",
  },
  progressBar: {
    height: 8,
    backgroundColor: "#e2e8f0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#ed8936",
  },
  configureSection: {
    backgroundColor: "#dbeafe",
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginTop: 8,
  },
  configureTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1e3a8a",
    textAlign: "center",
    marginBottom: 20,
  },
  configCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1.2,
    borderColor: "#354062ff",
  },
  configHeader: {
    marginBottom: 16,
  },
  configLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2D3E50",
    marginBottom: 4,
  },
  configHint: {
    fontSize: 12,
    color: "#90A4AE",
  },
  classListContainer: {
    paddingVertical: 8,
  },
  classButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginRight: 8,
    backgroundColor: "#ECEFF1",
    borderWidth: 1,
    borderColor: "#B0BEC5",
  },
  classButtonActive: {
    backgroundColor: "#3d4a72",
    borderColor: "#354062ff",
  },
  classButtonText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#2D3E50",
  },
  classButtonTextActive: {
    color: "#FFFFFF",
  },
  msgContainer: {
    backgroundColor: "#d4f3e8",
    borderRadius: 12,
    paddingVertical: 10,
    marginHorizontal: 10,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: "#a8e6d5",
  },
  content: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  checkmark: {
    fontSize: 20,
    color: "#2ecc71",
    marginRight: 8,
    fontWeight: "bold",
  },
  message: {
    fontSize: 16,
    color: "#27ae60",
    fontWeight: "600",
  },
  streamCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1.2,
    borderColor: "#354062ff",
  },
  streamHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  streamNumberBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#3d4a72",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  streamNumber: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  streamTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2D3E50",
    marginBottom: 4,
  },
  streamHint: {
    fontSize: 12,
    color: "#90A4AE",
  },
  streamsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  streamButton: {
    width: "48%",
    backgroundColor: "#ECEFF1",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#B0BEC5",
  },
  streamButtonActive: {
    backgroundColor: "#3d4a72",
    borderColor: "#3d4a72",
  },
  streamIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  streamButtonTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2D3E50",
    marginBottom: 4,
  },
  streamButtonDescription: {
    fontSize: 11,
    color: "#90A4AE",
    textAlign: "center",
  },
  subjectsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  subjectButton: {
    width: "48%",
    backgroundColor: "#ECEFF1",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#B0BEC5",
  },
  subjectButtonActive: {
    backgroundColor: "#3d4a72",
    borderColor: "#3d4a72",
  },
  subjectIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  subjectName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#2D3E50",
    textAlign: "center",
  },
  optionalLabel: {
    fontSize: 10,
    color: "#90A4AE",
    marginTop: 4,
    fontStyle: "italic",
  },
});

export default styles;